### ISSUE TITLE
Develop installation from source fails because of prettytensor dependence

### ISSUE THREAD

**Issue by wpm** [jkahn/samyro#2]
I did the following to install samyro

```
conda create --name samyro --channel https://conda.anaconda.org/conda-forge tensorflow
source activate samyro
git clone https://github.com/wpm/samyro.git
cd samyro
python setup.py develop
```

(My fork of the code is identical to your original.)
I get this error.

```
error: tensorflow 0.8.0 is installed but tensorflow>=0.9.0rc0 is required by set(['prettytensor'])
```

However, `pip install samyro` succeeds.

**Comment by wpm** [comment]
[full samyro error.txt](https://github.com/jkahn/samyro/files/320725/full.samyro.error.txt)

**Comment by wpm** [comment]
Same issue if I create a Python 3.4 Conda environment.

```
conda create --name samyro --channel https://conda.anaconda.org/conda-forge tensorflow python=3.4
```

However, `python setup.py install` installs the package without error.

**Comment by wpm** [comment]
However, when I try to run samyro in my Python 3 environment, the prettytensor version error still manifests:

```
> samyro learn timecube.cli 
Traceback (most recent call last):
  File "//anaconda/envs/samyro/lib/python3.4/site-packages/setuptools-23.0.0-py3.4.egg/pkg_resources/__init__.py", line 635, in _build_master
  File "//anaconda/envs/samyro/lib/python3.4/site-packages/setuptools-23.0.0-py3.4.egg/pkg_resources/__init__.py", line 943, in require
  File "//anaconda/envs/samyro/lib/python3.4/site-packages/setuptools-23.0.0-py3.4.egg/pkg_resources/__init__.py", line 834, in resolve
pkg_resources.ContextualVersionConflict: (tensorflow 0.8.0 (/anaconda/envs/samyro/lib/python3.4/site-packages), Requirement.parse('tensorflow>=0.9.0rc0'), {'prettytensor'})

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "//anaconda/envs/samyro/bin/samyro", line 5, in <module>
    from pkg_resources import load_entry_point
  File "<frozen importlib._bootstrap>", line 2237, in _find_and_load
  File "<frozen importlib._bootstrap>", line 2226, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 1191, in _load_unlocked
  File "<frozen importlib._bootstrap>", line 1161, in _load_backward_compatible
  File "//anaconda/envs/samyro/lib/python3.4/site-packages/setuptools-23.0.0-py3.4.egg/pkg_resources/__init__.py", line 2927, in <module>
  File "//anaconda/envs/samyro/lib/python3.4/site-packages/setuptools-23.0.0-py3.4.egg/pkg_resources/__init__.py", line 2913, in _call_aside
  File "//anaconda/envs/samyro/lib/python3.4/site-packages/setuptools-23.0.0-py3.4.egg/pkg_resources/__init__.py", line 2940, in _initialize_master_working_set
  File "//anaconda/envs/samyro/lib/python3.4/site-packages/setuptools-23.0.0-py3.4.egg/pkg_resources/__init__.py", line 637, in _build_master
  File "//anaconda/envs/samyro/lib/python3.4/site-packages/setuptools-23.0.0-py3.4.egg/pkg_resources/__init__.py", line 650, in _build_from_requirements
  File "//anaconda/envs/samyro/lib/python3.4/site-packages/setuptools-23.0.0-py3.4.egg/pkg_resources/__init__.py", line 834, in resolve
pkg_resources.ContextualVersionConflict: (tensorflow 0.8.0 (/anaconda/envs/samyro/lib/python3.4/site-packages), Requirement.parse('tensorflow>=0.9.0rc0'), {'prettytensor'})
```

**Comment by wpm** [comment]
The issue is that https://conda.anaconda.org/conda-forge only has tensorflow 0.8.0. The latest version is 0.9.0, and prettytensor relies on this one.

You can get this to work by directly running

```
pip install --upgrade https://storage.googleapis.com/tensorflow/mac/tensorflow-0.9.0rc0-py3-none-any.whl
```

instead of install tensorflow via Conda.

**Comment by wpm** [comment]
I'm not sure if you want to address this by upping the tensorflow version requirement to 0.9.0rc0 or holding prettytensor to an earlier version. (Though I imagine it's the former.)

**Comment by jkahn** [comment]
FWIW, Bill's suggested install instructions fail for me because he's using mac;  the [Google install instructions](https://www.tensorflow.org/versions/r0.9/get_started/os_setup.html) have a different path for my Linux (no-GPU) machine:
